[package]
name = "mark_1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
is31fl3731 = {version = "1.0.0", features = ["charlie_bonnet"]}
rppal = {version = "0.13.1", features = ["hal"]}
